# Generated by Django 5.2.8 on 2025-11-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parentprofile_parent_id_studentprofile_section_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
