# Generated by Django 5.2.8 on 2025-11-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assessment_assessmentscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentscore',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='assessmentscore',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='AssessmentScore',
        ),
    ]
