# Generated by Django 5.2.8 on 2025-11-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification_enhancements'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_recipie_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='core_notifi_recipie_1d5476_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_key'], name='core_notifi_notific_abf5df_idx'),
        ),
    ]
