# Generated by Django 5.2.8 on 2025-12-31 12:22

from django.db import migrations, connection


def add_code_column_if_missing(apps, schema_editor):
    """
    Add the 'code' and 'name' columns to core_subject table if they don't exist.
    Populate them from core_subjectmaster table using subject_master_id.
    This handles cases where the database schema is out of sync.
    """
    with connection.cursor() as cursor:
        # Check if the columns exist by querying table_info
        cursor.execute("PRAGMA table_info(core_subject)")
        columns = [row[1] for row in cursor.fetchall()]
        
        # Add code column if missing
        if 'code' not in columns:
            cursor.execute("""
                ALTER TABLE core_subject 
                ADD COLUMN code varchar(20) DEFAULT ''
            """)
            
            # Populate code from subject_master if subject_master_id exists
            cursor.execute("""
                UPDATE core_subject 
                SET code = (
                    SELECT sm.code 
                    FROM core_subjectmaster sm 
                    WHERE sm.id = core_subject.subject_master_id
                )
                WHERE subject_master_id IS NOT NULL
            """)
        
        # Add name column if missing
        if 'name' not in columns:
            cursor.execute("""
                ALTER TABLE core_subject 
                ADD COLUMN name varchar(100) DEFAULT ''
            """)
            
            # Populate name from subject_master if subject_master_id exists
            cursor.execute("""
                UPDATE core_subject 
                SET name = (
                    SELECT sm.name 
                    FROM core_subjectmaster sm 
                    WHERE sm.id = core_subject.subject_master_id
                )
                WHERE subject_master_id IS NOT NULL
            """)


def reverse_add_code_column(apps, schema_editor):
    """
    Reverse migration - remove the code column if it was added by this migration.
    Note: SQLite doesn't support DROP COLUMN directly, so this is a no-op.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_attendance_options_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            add_code_column_if_missing,
            reverse_add_code_column,
        ),
    ]
