# Generated by Django 5.2.8 on 2025-01-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_subject_code_if_missing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject_assignments', to='core.classsection')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='core.teacherprofile')),
            ],
            options={
                'verbose_name': 'Teacher Subject Assignment',
                'verbose_name_plural': 'Teacher Subject Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='teachersubjectassignment',
            index=models.Index(fields=['teacher', 'section'], name='core_teache_teacher__idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubjectassignment',
            index=models.Index(fields=['subject', 'section'], name='core_teache_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubjectassignment',
            index=models.Index(fields=['teacher', 'subject'], name='core_teache_teacher__idx2'),
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectassignment',
            unique_together={('teacher', 'subject', 'section')},
        ),
    ]

