# Generated by Django 5.2.8 on 2025-12-31 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_yearlevel_normalization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsection',
            options={'verbose_name': 'Class Section', 'verbose_name_plural': 'Class Sections'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.RemoveIndex(
            model_name='studentprofile',
            name='core_studen_section_7ed467_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentprofile',
            name='core_student_section_year_idx',
        ),
        migrations.RenameIndex(
            model_name='classsection',
            new_name='core_classs_year_le_540d0a_idx',
            old_name='core_classs_year_le_idx',
        ),
        migrations.RenameIndex(
            model_name='classsection',
            new_name='core_classs_year_le_7ca188_idx',
            old_name='core_classs_year_le_idx2',
        ),
        migrations.RenameIndex(
            model_name='studentenrollment',
            new_name='core_studen_student_eb9a7c_idx',
            old_name='core_studen_student__idx',
        ),
        migrations.RenameIndex(
            model_name='studentenrollment',
            new_name='core_studen_subject_9905ff_idx',
            old_name='core_studen_subject__idx',
        ),
        migrations.RenameIndex(
            model_name='studentenrollment',
            new_name='core_studen_student_ccd71a_idx',
            old_name='core_studen_student__idx2',
        ),
        migrations.RenameIndex(
            model_name='studentprofile',
            new_name='core_studen_year_le_f91a38_idx',
            old_name='core_studen_year_le_idx',
        ),
        migrations.RenameIndex(
            model_name='studentprofile',
            new_name='core_studen_year_le_58577a_idx',
            old_name='core_studen_year_le_idx2',
        ),
        migrations.RenameIndex(
            model_name='teachersubjectassignment',
            new_name='core_teache_teacher_9dfc36_idx',
            old_name='core_teache_teacher__idx',
        ),
        migrations.RenameIndex(
            model_name='teachersubjectassignment',
            new_name='core_teache_subject_a8fd79_idx',
            old_name='core_teache_subject_idx',
        ),
        migrations.RenameIndex(
            model_name='teachersubjectassignment',
            new_name='core_teache_teacher_727b8c_idx',
            old_name='core_teache_teacher__idx2',
        ),
        migrations.RenameIndex(
            model_name='yearlevel',
            new_name='core_yearle_level_ddb5be_idx',
            old_name='core_yearle_level_idx',
        ),
        migrations.RenameIndex(
            model_name='yearlevel',
            new_name='core_yearle_is_acti_3c3cae_idx',
            old_name='core_yearle_is_acti_idx',
        ),
        migrations.AlterField(
            model_name='classsection',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_sections', to='core.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.classsection'),
        ),
    ]
