# Generated by Django 5.2.8 on 2026-01-01 06:38

import django.db.models.deletion
from django.db import migrations, models


def drop_views(apps, schema_editor):
    """Drop database views and triggers that reference tables being altered"""
    with schema_editor.connection.cursor() as cursor:
        # Drop views
        cursor.execute("DROP VIEW IF EXISTS vw_teacher_subject_stats;")
        cursor.execute("DROP VIEW IF EXISTS vw_attendance_summary;")
        cursor.execute("DROP VIEW IF EXISTS vw_student_performance;")
        
        # Drop triggers that reference tables being altered
        cursor.execute("DROP TRIGGER IF EXISTS trg_validate_assessment_score;")
        cursor.execute("DROP TRIGGER IF EXISTS trg_validate_assessment_score_update;")
        cursor.execute("DROP TRIGGER IF EXISTS trg_grade_audit;")


def drop_index_if_exists(apps, schema_editor):
    """Drop indexes only if they exist - using IF EXISTS to handle gracefully"""
    indexes_to_drop = [
        'core_assess_subject_5154f9_idx',
        'core_assess_subject_8cbf31_idx',
        'core_assess_student_f268a5_idx',
        'core_attend_student_931c39_idx',
        'core_attend_subject_04fbb8_idx',
        'core_attend_student_bf410f_idx',
        'core_grade_student_37b337_idx',
        'core_grade_student_63d6fe_idx',
        'core_grade_subject_e2d92e_idx',
        'core_studen_subject_9905ff_idx',
        'core_studen_student_ccd71a_idx',
        'core_subjec_teacher_a2714d_idx',
        'core_subjec_section_53e29f_idx',
    ]
    
    with schema_editor.connection.cursor() as cursor:
        for index_name in indexes_to_drop:
            # Use IF EXISTS to safely drop index - won't error if it doesn't exist
            try:
                cursor.execute(f"DROP INDEX IF EXISTS {index_name};")
            except Exception:
                # Ignore any errors - index might not exist
                pass


def drop_constraints_if_exists(apps, schema_editor):
    """Drop constraints only if they exist"""
    constraints_to_drop = [
        ('core_attendance', 'unique_attendance_per_day'),
        ('core_attendance', 'unique_attendance_per_day'),
        ('core_grade', 'unique_grade_per_term'),
    ]
    
    with schema_editor.connection.cursor() as cursor:
        # For SQLite, constraints are part of table definition, so we need to check differently
        # We'll use a more lenient approach - try to drop and ignore errors
        try:
            cursor.execute("""
                SELECT sql FROM sqlite_master 
                WHERE type='table' AND name='core_attendance'
            """)
            result = cursor.fetchone()
            if result and 'unique_attendance_per_day' in result[0]:
                # Constraint exists, will be handled by RemoveConstraint operation
                pass
        except:
            pass
        
        try:
            cursor.execute("""
                SELECT sql FROM sqlite_master 
                WHERE type='table' AND name='core_grade'
            """)
            result = cursor.fetchone()
            if result and 'unique_grade_per_term' in result[0]:
                # Constraint exists, will be handled by RemoveConstraint operation
                pass
        except:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_classsection_options_and_more'),
    ]

    operations = [
        # Disable foreign key checks for SQLite (must be first)
        migrations.RunSQL(
            sql="PRAGMA foreign_keys = OFF;",
            reverse_sql="PRAGMA foreign_keys = ON;"
        ),
        # Drop views and triggers first to avoid errors during table alterations
        migrations.RunPython(drop_views, migrations.RunPython.noop),
        # Drop indexes conditionally (only if they exist)
        migrations.RunPython(drop_index_if_exists, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-date', 'name'], 'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
        migrations.AlterModelOptions(
            name='assessmentscore',
            options={'ordering': ['-created_at'], 'verbose_name': 'Assessment Score', 'verbose_name_plural': 'Assessment Scores'},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'enrollment'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-term', 'enrollment'], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['code'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        # Update state to reflect constraint removal (actual removal happens during table recreation)
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Constraints removed automatically during table recreation
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='attendance',
                    name='unique_attendance_per_day',
                ),
                migrations.RemoveConstraint(
                    model_name='grade',
                    name='unique_grade_per_term',
                ),
            ]
        ),
        # Index removals are handled by drop_index_if_exists function above
        # Remove old unique_together constraints before removing fields
        # (Django will try to recreate them during table recreation)
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),  # Clear old unique_together
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),  # Clear old unique_together
        ),
        migrations.AlterUniqueTogether(
            name='assessmentscore',
            unique_together=set(),  # Clear old unique_together
        ),
        migrations.AlterUniqueTogether(
            name='categoryweights',
            unique_together=set(),  # Clear old unique_together
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together=set(),  # Clear old unique_together
        ),
        # Remove indexes that reference old fields from state before removing fields
        # This prevents Django from trying to recreate them during table recreation
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Assessment indexes
                migrations.RemoveIndex(
                    model_name='assessment',
                    name='core_assess_subject_5154f9_idx',
                ),
                migrations.RemoveIndex(
                    model_name='assessment',
                    name='core_assess_subject_8cbf31_idx',
                ),
                # Attendance indexes
                migrations.RemoveIndex(
                    model_name='attendance',
                    name='core_attend_student_931c39_idx',
                ),
                migrations.RemoveIndex(
                    model_name='attendance',
                    name='core_attend_subject_04fbb8_idx',
                ),
                migrations.RemoveIndex(
                    model_name='attendance',
                    name='core_attend_student_bf410f_idx',
                ),
                # Grade indexes
                migrations.RemoveIndex(
                    model_name='grade',
                    name='core_grade_student_37b337_idx',
                ),
                migrations.RemoveIndex(
                    model_name='grade',
                    name='core_grade_student_63d6fe_idx',
                ),
                migrations.RemoveIndex(
                    model_name='grade',
                    name='core_grade_subject_e2d92e_idx',
                ),
                # Subject indexes
                migrations.RemoveIndex(
                    model_name='subject',
                    name='core_subjec_teacher_a2714d_idx',
                ),
                migrations.RemoveIndex(
                    model_name='subject',
                    name='core_subjec_section_53e29f_idx',
                ),
            ],
            database_operations=[],  # Indexes already dropped by drop_index_if_exists
        ),
        # Now remove old fields
        migrations.RemoveField(
            model_name='assessment',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='section',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        # Add new fields
        migrations.AddField(
            model_name='assessment',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.teachersubjectassignment'),
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='core.studentenrollment'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.studentenrollment'),
        ),
        migrations.AddField(
            model_name='categoryweights',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_weights', to='core.teachersubjectassignment'),
        ),
        migrations.AddField(
            model_name='grade',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.studentenrollment'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.teachersubjectassignment'),
        ),
        # Now alter unique_together after fields are added
        migrations.AlterUniqueTogether(
            name='assessmentscore',
            unique_together={('enrollment', 'assessment')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryweights',
            unique_together={('assignment',)},
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('student', 'assignment')},
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, help_text='Optional subject description'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this subject is currently active'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(help_text='Unique subject code (e.g., CS101)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Subject name (e.g., Introduction to Programming)', max_length=100),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['assignment', 'date'], name='core_assess_assignm_4fb78e_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['assignment', 'term'], name='core_assess_assignm_86e8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentscore',
            index=models.Index(fields=['enrollment', 'assessment'], name='core_assess_enrollm_8b62cb_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['enrollment', 'date'], name='core_attend_enrollm_5d7cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['enrollment', 'date', 'status'], name='core_attend_enrollm_bb6e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['enrollment', 'term'], name='core_grade_enrollm_7f2c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['term', 'grade'], name='core_grade_term_960ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['assignment', 'is_active'], name='core_studen_assignm_a88448_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['student', 'assignment'], name='core_studen_student_e17810_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['assignment', 'is_active', 'student'], name='core_studen_assignm_77dc06_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_active'], name='core_subjec_is_acti_80b240_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubjectassignment',
            index=models.Index(fields=['teacher', 'section', 'subject'], name='core_teache_teacher_b94005_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('enrollment', 'date'), name='unique_attendance_per_day'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('enrollment', 'term'), name='unique_grade_per_term'),
        ),
        migrations.RemoveField(
            model_name='assessmentscore',
            name='student',
        ),
        migrations.RemoveField(
            model_name='categoryweights',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='subject',
        ),
        # Re-enable foreign key checks after migration
        migrations.RunSQL(
            sql="PRAGMA foreign_keys = ON;",
            reverse_sql="PRAGMA foreign_keys = OFF;"
        ),
    ]
