# Generated by Django 5.2.8 on 2026-01-03 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_assessment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Semester name (e.g., '1st Semester', '2nd Semester')", max_length=50)),
                ('academic_year', models.CharField(help_text="Academic year (e.g., '2025-2026')", max_length=20)),
                ('start_date', models.DateField(help_text='Semester start date')),
                ('end_date', models.DateField(help_text='Semester end date')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='upcoming', help_text='Current status of the semester', max_length=10)),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is the current active semester')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['-academic_year', '-start_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='assessmentscore',
            name='core_assess_student_f268a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentenrollment',
            name='core_studen_subject_9905ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentenrollment',
            name='core_studen_student_ccd71a_idx',
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['status', 'is_current'], name='core_semest_status_f0bd55_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['academic_year', 'status'], name='core_semest_academi_2e1ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['is_current'], name='core_semest_is_curr_37b6e8_idx'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Semester for this attendance record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='core.semester'),
        ),
        migrations.AddField(
            model_name='grade',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Semester for this grade', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='core.semester'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Semester for this enrollment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.semester'),
        ),
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Semester for this assignment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='core.semester'),
        ),
    ]
