# Generated by Django 5.2.8 on 2026-01-03 09:25

import django.db.models.deletion
from django.db import migrations, models


def add_semester_columns_if_missing(apps, schema_editor):
    """Add semester foreign key columns if they don't exist"""
    db = schema_editor.connection
    cursor = db.cursor()
    
    # Check and add semester_id to teachersubjectassignment
    try:
        cursor.execute("SELECT semester_id FROM core_teachersubjectassignment LIMIT 1")
    except Exception:
        # Column doesn't exist, add it
        cursor.execute("""
            ALTER TABLE core_teachersubjectassignment 
            ADD COLUMN semester_id INTEGER NULL REFERENCES core_semester(id);
        """)
    
    # Check and add semester_id to studentenrollment
    try:
        cursor.execute("SELECT semester_id FROM core_studentenrollment LIMIT 1")
    except Exception:
        cursor.execute("""
            ALTER TABLE core_studentenrollment 
            ADD COLUMN semester_id INTEGER NULL REFERENCES core_semester(id);
        """)
    
    # Check and add semester_id to attendance
    try:
        cursor.execute("SELECT semester_id FROM core_attendance LIMIT 1")
    except Exception:
        cursor.execute("""
            ALTER TABLE core_attendance 
            ADD COLUMN semester_id INTEGER NULL REFERENCES core_semester(id);
        """)
    
    # Check and add semester_id to grade
    try:
        cursor.execute("SELECT semester_id FROM core_grade LIMIT 1")
    except Exception:
        cursor.execute("""
            ALTER TABLE core_grade 
            ADD COLUMN semester_id INTEGER NULL REFERENCES core_semester(id);
        """)


def remove_semester_columns(apps, schema_editor):
    """Remove semester foreign key columns"""
    db = schema_editor.connection
    cursor = db.cursor()
    
    try:
        cursor.execute("ALTER TABLE core_teachersubjectassignment DROP COLUMN semester_id")
    except Exception:
        pass
    
    try:
        cursor.execute("ALTER TABLE core_studentenrollment DROP COLUMN semester_id")
    except Exception:
        pass
    
    try:
        cursor.execute("ALTER TABLE core_attendance DROP COLUMN semester_id")
    except Exception:
        pass
    
    try:
        cursor.execute("ALTER TABLE core_grade DROP COLUMN semester_id")
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_semester_and_more'),
    ]

    operations = [
        migrations.RunPython(add_semester_columns_if_missing, remove_semester_columns),
    ]
