# Generated by Django 5.2.8 on 2026-01-03 09:30

from django.db import migrations


def add_semester_columns_if_missing(apps, schema_editor):
    """Add missing columns to Semester table if they don't exist"""
    db = schema_editor.connection
    cursor = db.cursor()
    
    # Get existing columns
    cursor.execute("PRAGMA table_info(core_semester)")
    existing_columns = [row[1] for row in cursor.fetchall()]
    
    # Define columns to add with their SQL definitions
    columns_to_add = {
        'name': "ALTER TABLE core_semester ADD COLUMN name VARCHAR(50) DEFAULT ''",
        'academic_year': "ALTER TABLE core_semester ADD COLUMN academic_year VARCHAR(20) DEFAULT ''",
        'start_date': "ALTER TABLE core_semester ADD COLUMN start_date DATE",
        'end_date': "ALTER TABLE core_semester ADD COLUMN end_date DATE",
        'status': "ALTER TABLE core_semester ADD COLUMN status VARCHAR(10) DEFAULT 'upcoming'",
        'is_current': "ALTER TABLE core_semester ADD COLUMN is_current BOOLEAN DEFAULT 0",
        'created_at': "ALTER TABLE core_semester ADD COLUMN created_at DATETIME",
        'updated_at': "ALTER TABLE core_semester ADD COLUMN updated_at DATETIME",
    }
    
    # Add missing columns
    for column_name, sql in columns_to_add.items():
        if column_name not in existing_columns:
            try:
                cursor.execute(sql)
                print(f"Added column: {column_name}")
            except Exception as e:
                print(f"Error adding column {column_name}: {e}")


def remove_semester_columns(apps, schema_editor):
    """Remove columns (reverse migration - not typically needed)"""
    # SQLite doesn't support DROP COLUMN easily, so we'll leave this empty
    # If needed, we'd have to recreate the table
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_semester_foreign_keys'),
    ]

    operations = [
        migrations.RunPython(add_semester_columns_if_missing, remove_semester_columns),
    ]
