# Generated by Django 5.2.8 on 2026-01-03 09:30

from django.db import migrations, models


def add_semester_indexes(apps, schema_editor):
    """Add indexes to Semester table if they don't exist"""
    db = schema_editor.connection
    cursor = db.cursor()
    
    # Get existing indexes
    cursor.execute("SELECT name FROM sqlite_master WHERE type='index' AND tbl_name='core_semester'")
    existing_indexes = [row[0] for row in cursor.fetchall()]
    
    indexes_to_add = [
        ('core_semest_status_f0bd55_idx', 'CREATE INDEX core_semest_status_f0bd55_idx ON core_semester (status, is_current)'),
        ('core_semest_academi_2e1ff0_idx', 'CREATE INDEX core_semest_academi_2e1ff0_idx ON core_semester (academic_year, status)'),
        ('core_semest_is_curr_37b6e8_idx', 'CREATE INDEX core_semest_is_curr_37b6e8_idx ON core_semester (is_current)'),
    ]
    
    for index_name, sql in indexes_to_add:
        if index_name not in existing_indexes:
            try:
                cursor.execute(sql)
                print(f"Added index: {index_name}")
            except Exception as e:
                print(f"Error adding index {index_name}: {e}")


def remove_semester_indexes(apps, schema_editor):
    """Remove indexes"""
    db = schema_editor.connection
    cursor = db.cursor()
    
    indexes_to_remove = [
        'core_semest_status_f0bd55_idx',
        'core_semest_academi_2e1ff0_idx',
        'core_semest_is_curr_37b6e8_idx',
    ]
    
    for index_name in indexes_to_remove:
        try:
            cursor.execute(f"DROP INDEX IF EXISTS {index_name}")
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_fix_semester_table_structure'),
    ]

    operations = [
        migrations.RunPython(add_semester_indexes, remove_semester_indexes),
    ]
