# Generated by Django 5.2.8 on 2026-01-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_semester_indexes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentscore',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='categoryweights',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectassignment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='semester',
        ),
        migrations.AddConstraint(
            model_name='assessmentscore',
            constraint=models.UniqueConstraint(fields=('enrollment', 'assessment'), name='unique_enrollment_assessment_score'),
        ),
        migrations.AddConstraint(
            model_name='categoryweights',
            constraint=models.UniqueConstraint(fields=('assignment',), name='unique_assignment_category_weights'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'assignment'), name='unique_student_assignment_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='teachersubjectassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'section'), name='unique_teacher_subject_section'),
        ),
    ]
