# Generated by Django 5.2.8 on 2026-01-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_refactor_semester_normalization'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teachersubjectassignment',
            name='unique_teacher_subject_section',
        ),
        migrations.AddConstraint(
            model_name='teachersubjectassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'section', 'semester'), name='unique_teacher_subject_section_semester'),
        ),
    ]
