# Generated by Django 5.2.8 on 2026-01-04 00:55

from django.db import migrations


def migrate_school_year_to_academic_year(apps, schema_editor):
    """
    Migrate data from school_year to academic_year and drop school_year column.
    This fixes the schema mismatch where the database has school_year (NOT NULL)
    but the model uses academic_year.
    """
    db = schema_editor.connection
    cursor = db.cursor()
    
    # Step 1: Copy data from school_year to academic_year where academic_year is empty
    cursor.execute("""
        UPDATE core_semester 
        SET academic_year = school_year 
        WHERE (academic_year IS NULL OR academic_year = '') 
        AND school_year IS NOT NULL 
        AND school_year != ''
    """)
    
    # Step 2: Drop the school_year column
    # SQLite doesn't support DROP COLUMN directly, so we need to recreate the table
    # First, get all data
    cursor.execute("SELECT id, name, academic_year, start_date, end_date, status, is_current, created_at, updated_at FROM core_semester")
    rows = cursor.fetchall()
    
    # Create new table without school_year
    cursor.execute("""
        CREATE TABLE core_semester_new (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name VARCHAR(50) NOT NULL,
            academic_year VARCHAR(20) NOT NULL,
            start_date DATE NOT NULL,
            end_date DATE NOT NULL,
            status VARCHAR(10) NOT NULL DEFAULT 'upcoming',
            is_current BOOLEAN NOT NULL DEFAULT 0,
            created_at DATETIME,
            updated_at DATETIME
        )
    """)
    
    # Copy data to new table
    cursor.executemany("""
        INSERT INTO core_semester_new 
        (id, name, academic_year, start_date, end_date, status, is_current, created_at, updated_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, rows)
    
    # Drop old table
    cursor.execute("DROP TABLE core_semester")
    
    # Rename new table
    cursor.execute("ALTER TABLE core_semester_new RENAME TO core_semester")
    
    # Recreate indexes
    cursor.execute("CREATE INDEX IF NOT EXISTS core_semest_status_f0bd55_idx ON core_semester (status, is_current)")
    cursor.execute("CREATE INDEX IF NOT EXISTS core_semest_academi_2e1ff0_idx ON core_semester (academic_year, status)")
    cursor.execute("CREATE INDEX IF NOT EXISTS core_semest_is_curr_37b6e8_idx ON core_semester (is_current)")
    
    print(f"Migrated {len(rows)} semester records from school_year to academic_year")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - add school_year column back (for rollback purposes)
    """
    db = schema_editor.connection
    cursor = db.cursor()
    
    # Add school_year column
    cursor.execute("ALTER TABLE core_semester ADD COLUMN school_year VARCHAR(20) NOT NULL DEFAULT ''")
    
    # Copy academic_year to school_year
    cursor.execute("UPDATE core_semester SET school_year = academic_year WHERE school_year = ''")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_semester_to_assignment_unique_constraint'),
    ]

    operations = [
        migrations.RunPython(
            migrate_school_year_to_academic_year,
            reverse_migration
        ),
    ]
